mod 'puppetlabs-apt', '7.3.0'
mod 'puppetlabs-stdlib', '6.2.0'
mod 'puppetlabs-translate', '2.1.0'
mod 'puppetlabs/concat'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '3.9.0'
mod 'puppetlabs-powershell', '2.3.0'
mod 'puppetlabs-reboot', '2.3.0'